### ISSUE TITLE
Intellij Plugin Instructions

### ISSUE THREAD

**Issue by jfbrennan** [klamborowski/JacksonGenerator#1]
Your instructions say: 
How to use:
• Select folder from Project Window , click RMB > New > JacksonGenerator

What is 'RMB'? I'd love to use this plugin but I don't see anything that even looks like it could be "RMB"...

I'm using Intellij 13.1 if that helps

**Comment by arpitanand** [comment]
@jfbrennan: i guess RMB is 'Right mouse button' i.e. right click.

**Comment by klamborowski** [comment]
@arpitanand is right, RMB means 'Right mouse button'.
